### ISSUE TITLE
Can not use post order api?

### ISSUE THREAD

**Issue by zskyfall** [felixbrucker/bitmart-api#2]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - NodeJs Version [e.g. 10]

**Additional context**

**Comment by felixbrucker** [comment]
Please provide all the details the issue template asked for.

**Comment by zskyfall** [comment]
I use post order api but i received this error: "Ivalid X-BM-SIGNATURE"

**Comment by felixbrucker** [comment]
Can you post an example code to reproduce the problem?
